[package]
name = "rpg_classic"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.7"
tower = "0.4"
tokio = { version = "1.48.0", features = ["full"] }
tower-http = { version = "0.5", features = ["trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt"] }
